# fly.toml app configuration file generated for doordash-order-parser on 2025-09-26T20:47:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doordash-order-parser'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 0
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
